env:
  global:
    - CC_TEST_REPORTER_ID=91a99bc5e719b898775fbec02c0ec66c9c8904cda7a44cc4ecb88817c1129e09
sudo: false
language: ruby
rvm:
  - ruby-head
  - 2.0
  - 2.1
  - 2.2
  - 2.3
  - 2.4
  - 2.5
  - 2.6
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
cache:
  - bundler
  - directories:
     - /home/travis/.rvm/
script: bundle exec rspec -fd
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
