sudo: false
language: ruby
cache: bundler

matrix:
  include:
  - rvm: ruby-head
    gemfile: Gemfile
  - rvm: 2.5
    gemfile: Gemfile
  - rvm: 2.4
    gemfile: Gemfile
  - rvm: 2.3
    gemfile: Gemfile
  - rvm: 2.2
    gemfile: Gemfile
  - rvm: 2.1
    gemfile: Gemfile
  - rvm: 2.0
    gemfile: Gemfile

script: bundle exec rspec spec
